### ISSUE TITLE
Synology x86_64 libz.so.1

### ISSUE THREAD

**Issue by JMPFFFFFFFF** [laktak/chkbit#12]
Works great on my Windows Machine. Trying to get it to work on LINUX DMS (Synology NAS) but I get this error
./chkbit: error while loading shared libraries: libz.so.1: failed to map segment from shared object

Would it be possible to get a copy of the required library file so I can drop it in the same directory? The Synology linux distro is so scaled down it's hard to even install dependencies.

**Comment by laktak** [comment]
What CPU does your NAS use? If it is not amd64, does it support Python >= 3.7?

**Comment by JMPFFFFFFFF** [comment]
uname --machinex86_64
Celeron J4025
pythonPython 3.8.15 (default, Nov 24 2022, 04:20:39)[GCC 12.2.0] on linuxType "help", "copyright", "credits" or "license" for more information.

    On Monday, March 4, 2024 at 04:49:37 PM EST, Christian Zangl ***@***.***> wrote:  
 
 


What CPU does your NAS use? If it is not amd64, does it support Python >= 3.7?

**Comment by laktak** [comment]
[This](https://www.reddit.com/r/learnpython/comments/b5bwz3/issue_with_libzso1_after_using_pyinstaller_and/) may be relevant.

Since you have python on the system you could also try to install via pipx (see README).
