### ISSUE TITLE
Homebrew listing

### ISSUE THREAD

**Issue by dia3olik** [laktak/chkbit#14]
Hey guys, just noticed you now have 75 stars here so maybe you can list chkbit on Homebrew?
It's so handy and it would help the project get more users!
Thanks for your work btw!!!!!

**Comment by laktak** [comment]
I'm working on it ;) https://github.com/Homebrew/homebrew-core/pull/175817

**Comment by laktak** [comment]
It's now available on homebrew :)

https://formulae.brew.sh/formula/chkbit
