### ISSUE TITLE
Intel build for macOS

### ISSUE THREAD

**Issue by bumper314** [laktak/chkbit#15]
Any chance of getting an Intel build for macOS?  Bonus points if it can run on macOS 10.14 Mojave!

**Comment by laktak** [comment]
Installing via Homebrew is not an option for you?

GitHub has changed their Action Runners and I'm still trying to find documentation for this. I'm using Pyinstaller and need a Intel Mac runner to produce the binary.

For now you can get the binary from this version - the only relevant changes were to support Homebrew:

https://github.com/laktak/chkbit-py/releases/tag/v4.1.0

**Comment by bumper314** [comment]
Several of the dependencies fail to build via homebrew on macOS 10.14 and homebrew explicitly says 10.14 isn't supported so don't bother reporting the issue.

But yes, the [v4.1.0](https://github.com/laktak/chkbit-py/releases/tag/v4.1.0) build works just fine, thank you.
