### ISSUE TITLE
chkbit does not detect missing files or folders

### ISSUE THREAD

**Issue by bumper314** [laktak/chkbit#16]
Because the .chkbit files reside inside a folder and only contains information about files and not folders, if an entire folder disappears from the tree, this will not be caught during a `chkbit` verify.

**Comment by laktak** [comment]
You are correct, chkbit only checks files for data corruption. It does not detect missing files or folders.

Is that a feature you would be interested in? What is your use case?

**Comment by bumper314** [comment]
Given the stated goals:

> chkbit is a tool that ensures the safety of your files by checking if their data integrity remains intact over time, especially during transfers and backups. It helps detect issues like disk damage, filesystem errors, and malware interference.

It seems you would want to know if a whole folder goes missing (e.g. malware removed a whole folder, a backup/transfer was incomplete, etc).

So yes, I would put my vote toward this feature 👍

**Comment by laktak** [comment]
Hmm, it seems easy enough to implement. I'll add it to my list :)

**Comment by laktak** [comment]
Released in v5.2.0
