### ISSUE TITLE
Feature request: Add option to update modified files while not checking not modified files

### ISSUE THREAD

**Issue by lambdareader** [laktak/chkbit#19]
Thank you for developing such a great tool.
If someone wants to update the index they can only choose between -u and -a.
-u rechecks every file and updates the index if the timestamp is modified or files are added, while -a adds only new files.
Can you add a third option to add not just new files but also update all modified files if the timestamp changed, while not rechecking not modified files?
I would assume that not a lot of people completely update the index before doing a backup to a second drive due to the long time it takes and only run it beforehand with -a. This can lead to a scenario where one drive dies and it is unknown whether some of the modified files which have not been updated are corrupted or not. Even if there is no other copy it would be good to at least know that something has been corrupted.

Also what happened to chkbit-py? It redirects to this repo but is still available on pypi.

**Comment by laktak** [comment]
While I do not completely understand your use case it's a simple feature - I'll add it in the next release (been a bit busy).

chkbit-py is available in the python branch.

**Comment by laktak** [comment]
I though about this and decided to add it to the `-a` switch as that makes more sense:

    -a, --add-only                       add mode: only add new and modified files, 
                                         do not check existing (quicker)

**Comment by laktak** [comment]
After thinking about it I've included your request in the `-a` option which is now named "add new and modified files".

**Comment by varmint708** [comment]
not sure if this is right place to report, but the above feature doesn't work in version 6, can this be brought back? was there a reason this was removed?

$ chkbit version
github.com/laktak/chkbit
6.0.0

$ chkbit update --add-only .
<snip>...
chkbit: error: unknown flag --add-only

**Comment by laktak** [comment]
The cli was updated with v6. If you look two lines above the error 

```
  -s, --skip-existing                  only add new and modified files, do not check existing (quicker)
      --force                          force update of damaged items (advanced usage only)

chkbit: error: unknown flag --add-only
```

use `-s` (also `chkbit update --help`).

**Comment by varmint708** [comment]
That worked, Sorry still getting used to the new UI. Thanks!

**Comment by laktak** [comment]
No worries :)
