### ISSUE TITLE
Feature request: show only modified files in the screen output

### ISSUE THREAD

**Issue by y653** [laktak/chkbit#20]
I am using the program for few weeks now, and I think it is really good, and thank you for sharing it.

As of version 5.2.0, the program has two modes to show its output in the screen: one without -v flag, and the other with this flag. The first one only shows the number of files that are new, old or updated. It does not mention how many files are deleted from the .chksum files. I think that this is useful information. Furthermore, the -v mode shows all files, even the ones that are fine (definitely useful especially if it is combined with redirecting the whole output in a logfile to check it thoroughly), but the default mode (without -v) show very little info. It would be usefull to add another option (something in between these two) where it would show only the files that are different (old, new, deleted, updated, ...). As an example, in a directory a single file is deleted. In the default mode, only the info "1 directory was updated" is shown, and the user does not know neither that there was only one or more files deleted, neither which one(s).

Do you think this could be added in a following version?

**Comment by laktak** [comment]
Are you looking for

> -m, --show-missing                   show missing files/directories

because it does what you are asking for.

**Comment by y653** [comment]
Oh, yes, you are right! I have missed that option! That is great!
Thank you very much for this very useful tool!
