### ISSUE TITLE
Feature or bug? All .dot files are ignored

### ISSUE THREAD

**Issue by y653** [laktak/chkbit#21]
Hello again, and thanks your your great work.

I realised that all files beginning with a dot (.chkbit, .config, etc) are ignore from the checksuming process. I understand that this should be the default for .chkbit files that are produced during the checksumming phase, but what about all other .dot files? I have plenty of them in a linux PC, and I realised that these are not included in the checksums, even though I do not use any .chkbitignore file at all. I think that only .chkbit files should be excluded and all others only when they are included in the .chkbitignore file, possibly with wildcards (eg .conf*).

If you agree, you could probably include this change in a following version.

Again, thanks your your hard work!

**Comment by laktak** [comment]
They are not included by default but I'll add an option so you can include them if you wish.

**Comment by y653** [comment]
That would be great, thank you!! All the best!

**Comment by laktak** [comment]
I forgot to comment, that option is now included.

**Comment by y653** [comment]
Great thanks!
In the releases though I see still the 5.2.0 version, that does not have this option.

**Comment by laktak** [comment]
Well the idea is that you test this before I do a release.

If you cannot build the source yourself, I've added prerelease-artifacts:

> Prereleased versions can be found directly on the [Git Action](https://github.com/laktak/chkbit/actions). Click on the latest action and look for `prerelease-artifacts` at the bottom.

You can download the zip and then extract the binary for your platform.

**Comment by y653** [comment]
Thanks, I downloaded it.

**Comment by laktak** [comment]
I assume it works for you.

**Comment by y653** [comment]
Sorry, I did not have the time to test it. I tested it right now, and it works just fine! Thank you very much for your time!!
