### ISSUE TITLE
Question: how to avoid "permission denied"

### ISSUE THREAD

**Issue by huyz** [laktak/chkbit#23]
Sorry if this question has been answered elsewhere—I can't find anything.

How can we avoid `permission denied` when chkbit is trying to create its files in unwritable directories?  For example,

```
[…snip…]/HP Easy Start.app/Contents/_CodeSignature/.chkbit: permission denied     
```

I have this `.chkbitignore` at the root of the path that I invoke chkbit on:
```
_CodeSignature
```

But that doesn't seem to do it.

**Comment by laktak** [comment]
I found a bug in the ignore code. Can you test if this fixes the issue?

Download prerelease-artifacts from https://github.com/laktak/chkbit/actions/runs/12019167228

**Comment by huyz** [comment]
I can test this if you have a pre-release that centralizes the DB as well

**Comment by laktak** [comment]
I'll close this since you said you are not interested in testing.

**Comment by huyz** [comment]
That's not what I said. But ok

**Comment by laktak** [comment]
It's in the released version if you want to test it now.

**Comment by huyz** [comment]
@laktak It worked, thanks!
