### ISSUE TITLE
Preserve modification dates of directories

### ISSUE THREAD

**Issue by huyz** [laktak/chkbit#24]
Is there a way to run chkbit without affecting the directories' modification dates?
I happen to rely heavily on these modification dates, especially for sorting. I can't use chkbit this way.

**Comment by laktak** [comment]
That's a good idea! I didn't see any downsides so I made this the default.

Can you test https://github.com/laktak/chkbit/actions/runs/12036499335 (download prerelease-artifacts)?

**Comment by huyz** [comment]
Btw, for anyone who ran into this issue (before the new prerelease above), here's a script for restoring modification dates of subdirectories on macOS: https://github.com/huyz/trustytools/blob/master/contrib/restore-modified-date.sh

**Comment by huyz** [comment]
I don't think I can test this as I'll only run anything if there's a centralized DB. I get the argument for spreading files everywhere but I got a gazillion folders and I'd like to keep them nice and pristine.
Feel free to close this issue.

**Comment by laktak** [comment]
I'd consider it impolite to first ask for something and then not even bother to test it.

**Comment by huyz** [comment]
I appreciate your responsiveness and your work for sure.

It's just that I spent 3 days without further backups trying to recover the modification dates on hundreds of thousands of folders. I can't risk the modification dates being changed again. That was just too painful

**Comment by huyz** [comment]
I understand if you thought that was rude. I apologize. I wish I had said it differently

**Comment by y653** [comment]
I have not made attention to this issue up to now!! I have now the same problem, with all my folders having changed their date and time. huyz how did you reverted it back?

Update: I just saw the script you made for MacOS. I use Linux. Do you think that this should work in Linux as well? I guess that the "BACKUP_DIR" is a previous backup you have (eg in an external HDD) from which you restore the date/time info?

**Comment by huyz** [comment]
I'll try to update the script to use touch and stat to support Linux. 
Yes you must have backups. I assume you already do

Update: best if you remember the approximate dates you ran chkbit. Maybe I can improve the script to not restore the dates if the date is _after_ the last time you ran chkbit (because these would be legitimate modification dates that you wouldn't want to overwrite)

**Comment by y653** [comment]
Yes, of course I have backups. I also know the date I run chkbit, since it is the same shown in all directories! Thank you for your kind offer to update the script. When you have the time to update it, please let me know! Thanks a lot!

**Comment by laktak** [comment]
@huyz OK, no problem. 

I think you misunderstood me - when I ask for testing I simply ask you to run it on a couple of folders (could be your temp directory) and check if the issue is fixed.

**Comment by y653** [comment]
I downloaded the above prerelease version and it works fine with the directories dates and times! It does not change them!

**Comment by laktak** [comment]
:+1:  I'll release a new version with the fix.

**Comment by huyz** [comment]
@y653 I updated https://github.com/huyz/trustytools/blob/master/contrib/restore-modified-date.sh to support Linux (GNU coreutils tools) and have added an `--after` and `--before` flag. Try `restore-modified-date -h`
