### ISSUE TITLE
Very slow on spinning disks

### ISSUE THREAD

**Issue by vredesbyyrd** [laktak/chkbit#25]
Hi, thanks for sharing this tool. I started using it yesterday and it appears to be just what I have been looking for. 

chkbit --version: `e1979282c967dba1a6c52bf07fcdaa41ff69d9d0`

I turned an old laptop into a media/file server, its relatively low powered but does the job: 

- intel i5-4200u
- 10GB ram
- 1x16TB 7200
- 2x8TB 7200
- linux 6.12-1

My plan is to track photos and music/video with chkbit and keep an individual database for photos and one for music/video. This is all ran directly on the server, not through nfs or anything similar. On the photography directory I ran:

```
chkbit --init-db /mnt/TARS/Backup/Photography
chkbit --db --update /mnt/TARS/Backup/Photography
```
The db was created and populated successfully. I did this yesterday so I do not recall the exact length it took to index, but 60,000 photos took roughly an hour. For spinning rust that seems reasonable. The disk read speed was 170MB/s on average.

I'm trying to do the same for my music/movies/tv (50,000 files) and oddly it is moving at a snails pace. 

```
chkbit --init-db /mnt/TARS/Media
chkbit --db --update /mnt/TARS/Media
```
Disk read speed is still 170MB/s on average, but chkbit is reporting 0 files/s. After 40 minutes it's indexed 248 files. My `.chkbitignore` is pretty lengthy so I tried running with an empty `.chkbitignore` but it made no difference. Adding more workers also had no effect. 

I know using a database as opposed to individual files could be considered beta, maybe something going on there? If you have any ideas I am all ears! Thanks for your time. 

EDIT: For clarity, I also store my photos on an nvme drive that is my main "work" drive, unsurprising chkbit was able to index those files very quickly.

**Comment by laktak** [comment]
When you are on rust you should use just one worker `--workers=1`, so it can do sequential reads instead of spending time on seeking. Let me know if that helps.

**Comment by vredesbyyrd** [comment]
Thanks. `--workers=1` does speed it up on rust. Read speed increased to 200-270mb/s, although it's still processing about `0/1 files/s`. That's 14 hours, minimum, to index 50,000 files. Is that expected behavior on rust? 

When processing my photo directory it's stays fairly steady at `8 files/s`. That makes me wonder, is file size a variable on how quickly things are processed? Probably a stupid question. 

EDIT: if it comes down to it, I may just track my photos - those are the irreplaceable files. I did lose some photos to what I believe was bitrot in the past. Movies/tv can always be re-ripped/downloaded.

**Comment by y653** [comment]
I use chkbit on both SSDs and HDDs (internal and external). On HDDs (even my fastest WD Black series) I run many tests and in all of them (especially in the external ones) the use of one worker was significantly faster. For SSDs I keep the default settings.

For videos, since they are not so valuable, you could also try other algorithms, which could speed up the process.

**Comment by laktak** [comment]
> Thanks. --workers=1 does speed it up on rust. Read speed increased to 200-270mb/s

With one worker chkbit is just waiting for data, even the directory read-ahead is just workers*10.

I really can't help you with hardware issues. This depends on a lot of factors. If the disk isn't too fragmented you should see constant data rates. My external disks (though with lots of smaller files) shows half your throughput.

> For videos, since they are not so valuable, you could also try other algorithms, which could speed up the process.

The disk is usually the slowest part so the algorithm shouldn't make any difference.

**Comment by vredesbyyrd** [comment]
I much appreciate the tips. I'll close this, as it sounds like the speeds I am seeing are not out of the ordinary.

**Comment by vredesbyyrd** [comment]
Just a note. I let chkbit index my movie/tv/music dir (50,000), and it finished in 8.5 hours. That's much quicker than I initially assumed it would. Things sped up a lot once it got done with the largest video files. I plan on scrubbing those dirs once a month, so 8.5 is totally reasonable imo.
