### ISSUE TITLE
Additional logging info

### ISSUE THREAD

**Issue by vredesbyyrd** [laktak/chkbit#26]
Hi. 

Would it be possible to have a more verbose logging option that logs the duration/speed info?

On stdout we see something like:

```
- 0s elapsed
- 654.05 files/second
- 0.10 MB/second
```
I did try to disable built in logging altogether and redirect everything to the log with:

```shell
unbuffer chkbit --db --update --show-missing $SOURCE 2>&1 | tee $CHKBIT_LOG
```
But with that, the very nice progress bar also gets logged on every newline. IMO it can be nice to see how long, long running jobs are really taking.  

Any thoughts on such a feature? Thanks for your time.

**Comment by laktak** [comment]
Yes, that's a good suggestion! I'll add it to the next version.

**Comment by vredesbyyrd** [comment]
Awesome, thanks :)

Thinking about it more, imo it would be most sensible to just add the duration/speed info as default. It's only three lines, and a person may want that info but not verbose logging.

**Comment by vredesbyyrd** [comment]
Thanks for implementing this :+1:
